#############################################################################
# Makefile for building: Cube_TetraHedra
# Generated by qmake (3.0) (Qt 5.0.0) on: Sun Jun 9 19:26:45 2013
# Project:  Cube_TetraHedra.pro
# Template: app
# Command: /home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/bin/qmake -o Makefile Cube_TetraHedra.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/linux-g++-64 -I. -I. -I../../Dependencies/QT500/5.0.0/gcc_64/include -I../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui -I../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64 -Wl,-rpath,/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CMatrix.cpp \
		CQuat.cpp \
		CVector.cpp \
		glwidget.cpp \
		main.cpp \
		point.cpp \
		window.cpp \
		debug/qrc_textures.cpp \
		release/qrc_textures.cpp qrc_textures.cpp \
		moc_glwidget.cpp \
		moc_window.cpp
OBJECTS       = CMatrix.o \
		CQuat.o \
		CVector.o \
		glwidget.o \
		main.o \
		point.o \
		window.o \
		qrc_textures.o \
		qrc_textures.o \
		qrc_textures.o \
		moc_glwidget.o \
		moc_window.o
DIST          = ../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/linux.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/qconfig.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/spec_post.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/release.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/default_post.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/shared.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/resources.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/moc.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/yacc.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/lex.prf \
		Cube_TetraHedra.pro \
		textures.qrc \
		Cube_TetraHedra.pro
QMAKE_TARGET  = Cube_TetraHedra
DESTDIR       = 
TARGET        = Cube_TetraHedra


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Cube_TetraHedra.pro ../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf ../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/linux.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/qconfig.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/spec_post.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/release.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/default_post.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/shared.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/resources.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/moc.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/yacc.prf \
		../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/lex.prf \
		Cube_TetraHedra.pro \
		textures.qrc \
		/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/lib/libQt5Gui.prl \
		/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Cube_TetraHedra.pro
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/spec_pre.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/shell-unix.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/unix.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/linux.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/gcc-base.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/g++-base.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/common/g++-unix.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/qconfig.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt_functions.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt_config.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/spec_post.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/default_pre.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/default_pre.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/release.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/default_post.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/shared.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/warn_on.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/qt.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/resources.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/moc.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/opengl.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/unix/thread.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/wayland-scanner.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/testcase_targets.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/exceptions.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/yacc.prf:
../../Dependencies/QT500/5.0.0/gcc_64/mkspecs/features/lex.prf:
Cube_TetraHedra.pro:
textures.qrc:
/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/lib/libQt5Gui.prl:
/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Cube_TetraHedra.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Cube_TetraHedra1.0.0 || $(MKDIR) .tmp/Cube_TetraHedra1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Cube_TetraHedra1.0.0/ && $(COPY_FILE) --parents textures.qrc .tmp/Cube_TetraHedra1.0.0/ && $(COPY_FILE) --parents camera.h CMatrix.h CQuat.h CVector.h glwidget.h mathHelper.h point.h ui_MainWindow.h window.h .tmp/Cube_TetraHedra1.0.0/ && $(COPY_FILE) --parents CMatrix.cpp CQuat.cpp CVector.cpp glwidget.cpp main.cpp point.cpp window.cpp debug/qrc_textures.cpp release/qrc_textures.cpp .tmp/Cube_TetraHedra1.0.0/ && (cd `dirname .tmp/Cube_TetraHedra1.0.0` && $(TAR) Cube_TetraHedra1.0.0.tar Cube_TetraHedra1.0.0 && $(COMPRESS) Cube_TetraHedra1.0.0.tar) && $(MOVE) `dirname .tmp/Cube_TetraHedra1.0.0`/Cube_TetraHedra1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Cube_TetraHedra1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_textures.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_textures.cpp
qrc_textures.cpp: textures.qrc \
		images/side4.png \
		images/side3.png \
		images/side2.png \
		images/side6.png \
		images/side1.png \
		images/side5.png
	/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/bin/rcc -name textures textures.qrc -o qrc_textures.cpp

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: moc_glwidget.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glwidget.cpp moc_window.cpp
moc_glwidget.cpp: camera.h \
		CVector.h \
		mathHelper.h \
		glwidget.h
	/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_window.cpp: ui_MainWindow.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QVariant \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvariant.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qglobal.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qconfig.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfeatures.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlogging.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qflags.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbytearray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrefcount.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qnamespace.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstring.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qchar.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiterator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmetatype.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qisenum.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpair.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdebug.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qhash.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextstream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiodevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlocale.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qshareddata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvector.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpoint.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qset.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontiguouscache.h \
		window.h
	/home/pourya/Desktop/Projects/Dependencies/QT500/5.0.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

CMatrix.o: CMatrix.cpp CMatrix.h \
		CVector.h \
		mathHelper.h \
		CQuat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMatrix.o CMatrix.cpp

CQuat.o: CQuat.cpp CQuat.h \
		CVector.h \
		mathHelper.h \
		CMatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CQuat.o CQuat.cpp

CVector.o: CVector.cpp CVector.h \
		mathHelper.h \
		CMatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CVector.o CVector.cpp

glwidget.o: glwidget.cpp ../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QtGui \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QtCore \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qnamespace.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qglobal.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qconfig.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfeatures.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlogging.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qflags.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstring.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qchar.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbytearray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrefcount.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiterator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmetatype.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qisenum.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qanimationgroup.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpauseanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvariantanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qeasingcurve.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvector.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpoint.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvariant.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpair.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdebug.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qhash.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextstream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiodevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlocale.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qshareddata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qset.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextcodec.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qendian.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlibraryinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdatetime.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qnumeric.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbuffer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdatastream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdir.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfileinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfile.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qregexp.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdiriterator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocess.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qresource.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsettings.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstandardpaths.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtemporarydir.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QScopedPointer \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtemporaryfile.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qurl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qurlquery.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringlistmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsonarray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsonvalue.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsondocument.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsonobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qeventloop.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbasictimer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcoreapplication.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmath.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmetaobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmimedata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsharedmemory.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsignalmapper.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsocketnotifier.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtimer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtranslator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmimedatabase.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmimetype.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlibrary.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpluginloader.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/quuid.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractstate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstracttransition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qeventtransition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfinalstate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qhistorystate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsignaltransition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstatemachine.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qexception.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfuture.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfutureinterface.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrunnable.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmutex.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qresultstore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfuturewatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qreadwritelock.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsemaphore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qthread.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qthreadpool.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qthreadstorage.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qwaitcondition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydataops.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbitarray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcache.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcryptographichash.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qline.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlinkedlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmargins.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qqueue.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrect.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsize.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qregularexpression.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstack.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtimeline.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qxmlstream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtcoreversion.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessible.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qcolor.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qrgb.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qevent.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qregion.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvector2d.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtouchdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessible2.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessiblebridge.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessibleobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessibleplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qbitmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpixmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimage.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtransform.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qmatrix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpolygon.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpainterpath.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qicon.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qiconengine.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qiconengineplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimageiohandler.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimagereader.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimagewriter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qmovie.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpicture.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpictureformatplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpixmapcache.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qstandarditemmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qbrush.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfont.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qclipboard.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qcursor.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qdrag.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qgenericplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qgenericpluginfactory.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qguiapplication.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qinputmethod.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglcontext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QObject \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QSurfaceFormat \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopengl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopengles2ext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qt_windows.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpalette.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qscreen.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QList \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QRect \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QSize \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QSizeF \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QTransform \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsessionmanager.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qstylehints.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsurface.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qwindow.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QEvent \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QMargins \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvector3d.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvector4d.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qquaternion.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglpaintdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qbackingstore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpagedpaintdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpaintengine.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpainter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextoption.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpen.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpdfwriter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextlayout.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextformat.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qglyphrun.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qrawfont.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfontdatabase.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextcursor.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextdocument.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qstatictext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextdocumentfragment.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextdocumentwriter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtexttable.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qdesktopservices.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvalidator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QGenericPluginFactory \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QGenericPlugin \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtguiversion.h \
		glwidget.h \
		camera.h \
		CVector.h \
		mathHelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

main.o: main.cpp window.h \
		ui_MainWindow.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QVariant \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvariant.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qglobal.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qconfig.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfeatures.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlogging.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qflags.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbytearray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrefcount.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qnamespace.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstring.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qchar.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiterator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmetatype.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qisenum.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpair.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdebug.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qhash.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextstream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiodevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlocale.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qshareddata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvector.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpoint.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qset.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

point.o: point.cpp point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o point.cpp

window.o: window.cpp ../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QtGui \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QtCore \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qnamespace.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qglobal.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qconfig.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfeatures.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlogging.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qflags.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstring.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qchar.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbytearray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrefcount.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiterator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmetatype.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qisenum.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qanimationgroup.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpauseanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvariantanimation.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qeasingcurve.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvector.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpoint.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qvariant.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpair.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdebug.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qhash.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextstream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qiodevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlocale.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qshareddata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qset.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextcodec.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qendian.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlibraryinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdatetime.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qnumeric.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbuffer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdatastream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdir.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfileinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfile.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qregexp.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qdiriterator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocess.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qresource.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsettings.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstandardpaths.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtemporarydir.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QScopedPointer \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtemporaryfile.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qurl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qurlquery.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstringlistmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsonarray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsonvalue.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsondocument.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qjsonobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qeventloop.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbasictimer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcoreapplication.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmath.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmetaobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmimedata.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsharedmemory.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsignalmapper.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsocketnotifier.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtimer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtranslator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmimedatabase.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmimetype.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlibrary.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qpluginloader.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/quuid.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstractstate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qabstracttransition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qeventtransition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfinalstate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qhistorystate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsignaltransition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstate.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstatemachine.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qexception.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfuture.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfutureinterface.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrunnable.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmutex.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qresultstore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfuturewatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qreadwritelock.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsemaphore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qthread.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qthreadpool.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qthreadstorage.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qwaitcondition.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydataops.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbitarray.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcache.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcryptographichash.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qline.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlinkedlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qmargins.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qqueue.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qrect.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsize.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qregularexpression.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qstack.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtimeline.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qxmlstream.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtcoreversion.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessible.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qcolor.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qrgb.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qevent.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qregion.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvector2d.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtouchdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessible2.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessiblebridge.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessibleobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qaccessibleplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qbitmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpixmap.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimage.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtransform.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qmatrix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpolygon.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpainterpath.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qicon.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qiconengine.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qiconengineplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimageiohandler.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimagereader.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qimagewriter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qmovie.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpicture.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpictureformatplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpixmapcache.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qstandarditemmodel.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qbrush.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfont.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qclipboard.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qcursor.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qdrag.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qgenericplugin.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qgenericpluginfactory.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qguiapplication.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qinputmethod.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglcontext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QObject \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QSurfaceFormat \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopengl.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopengles2ext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qt_windows.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpalette.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qscreen.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QList \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QRect \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QSize \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QSizeF \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QTransform \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsessionmanager.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qstylehints.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsurface.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qwindow.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QEvent \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QMargins \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvector3d.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvector4d.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qquaternion.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglpaintdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qbackingstore.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpagedpaintdevice.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpaintengine.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpainter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextoption.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpen.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qpdfwriter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextlayout.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextformat.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qglyphrun.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qrawfont.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qfontdatabase.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextcursor.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextdocument.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qstatictext.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextobject.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextdocumentfragment.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextdocumentwriter.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtextlist.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtexttable.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qdesktopservices.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qvalidator.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QGenericPluginFactory \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/QGenericPlugin \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtGui/qtguiversion.h \
		glwidget.h \
		camera.h \
		CVector.h \
		mathHelper.h \
		window.h \
		ui_MainWindow.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/QVariant
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

qrc_textures.o: debug/qrc_textures.cpp ../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qglobal.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qconfig.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfeatures.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlogging.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qflags.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsysinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_textures.o debug/qrc_textures.cpp

qrc_textures.o: release/qrc_textures.cpp ../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qglobal.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qconfig.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qfeatures.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qlogging.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qflags.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Dependencies/QT500/5.0.0/gcc_64/include/QtCore/qsysinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_textures.o release/qrc_textures.cpp

qrc_textures.o: qrc_textures.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_textures.o qrc_textures.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

